node_id: "node3"
listen_addr: "0.0.0.0:9003"  # Docker: bind to all interfaces
raft_addr: "node3:9013"     # Docker: use service name for Raft
bootstrap: false
join_url: "http://node1:9001"  # Docker: use service name
peers:
  - "node1:9001"
  - "node2:9002"

