node_id: "node2"
listen_addr: "0.0.0.0:9002"  # Docker: bind to all interfaces
raft_addr: "node2:9012"      # Docker: use service name for Raft
bootstrap: false
join_url: "http://node1:9001"  # Docker: use service name
peers:
  - "node1:9001"
  - "node3:9003"

